### ISSUE TITLE
micro_asc_rda with hierarchies - inconsistent use of fixed-length fields breaks tau-argus

### ISSUE THREAD

**Issue by samkodes** [InseeFrLab/rtauargus#6]
When I run micro_asc_rda to create .asc and .rda files with a variable hierarchy, e.g.
micro_asc_rda(microdata = cd2.micro,hrc=c(CDNAME="CDNAME>Region"),asc_filename="cd2.micro.asc",rda_filename = "cd2.micro.rda")
the output .asc and .rda files used fixed-width format, resulting in lots of string padding in the .asc file.
However the generated .hrc file does NOT pad its strings.

When tau-argus is run using this set of outputs, it fails when it tries to generate a table with the error Message "Explore File went wring in line1 / Code not in codelist / Variable: CDNAME". 

If I manually edit the .hrc file to pad the strings to match the .asc file, for the first few rows (say the first 3), the error message then cites "line4" instead of line1.

I suspect the problem is that tau-argus is not automatically trimming strings when it processes a fixed-width .asc file.
One solution might be to output a variable-width .asc file? Another solution might be to make the .hrc levels match the padded strings.

Alternatively, I can try to recode my variables/levels to a fixed width.

**Comment by samkodes** [comment]
Update: Recoding levels to a fixed width before running micro_asc_rda fixed the problem.

**Comment by julienjamme** [comment]
Hello @samkodes : Indeed, Tau-argus requires same length codes for each one at the same level of the hierarchy. 
This issue is automatically managed if you use our tabular approach implemented in the `tab_rtauargus` - if you have one table to protect - or `tab_multi_manager` if you have several linked tables.
